##########  CREATE SNAPSHOT and UPLOAD TO AZURE STORAGE                                 ##########
##########  learn more http://docs.liquibase.com/flow                                   ##########
##########  This flow requires Azure CLI                                                ##########
##########  Download at https://learn.microsoft.com/en-us/cli/azure/install-azure-cli   ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  CLIENT_ID: ${AZURE_CREDS_USR}
  CLIENT_SECRET: ${AZURE_CREDS_PSW}
  TENANT_ID: ${AZURE_TENANT_ID}
  SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
  STORAGE_ACCT: ${AZURE_STORAGE_ACCOUNT}
  CONTAINER: ${AZURE_CONTAINER_NAME}
  
stages:
  Snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          {  snapshot-format: json }
        globalArgs: { output-file: 'snapshots/${ENV}-snapshot.json' }
        
      - type: shell
        command: echo 'Snapshot created as snapshots/${ENV}-snapshot.json'

  AzureUpload:
    actions:
      - type: shell
        command: | 
          az login --service-principal -u ${CLIENT_ID} -p ${CLIENT_SECRET} -t ${TENANT_ID}
          az account set --subscription ${SUBSCRIPTION_ID}
          az storage container create --account-name ${STORAGE_ACCT} --name ${CONTAINER}
          az storage blob upload-batch --destination ${CONTAINER} --source ./snapshots --account-name ${STORAGE_ACCT} --overwrite
          az logout