### Setup an environment variable with comma-separated db names called DATABASES

stages:
  liquibaseUpdate:
    # Run Update
    actions:
      - type: shell
        command: |
          set "dbs=%DATABASES%"
          set "dbs=%dbs:,= %"
          for %%D in (%dbs%) do (
            echo ### Deploying to %%D ###
            liquibase update --url=jdbc:sqlserver://demo-db1-win.liquibase.net:1433;databaseName=%%D;trustServerCertificate=true
          )
          

endStage:
  actions:
    # Show history
      - type: shell
        command: |
          set "dbs=%DATABASES%"
          set "dbs=%dbs:,= %"
          for %%D in (%dbs%) do (
            echo ### Deployment history for %%D ###
            liquibase history --url=jdbc:sqlserver://demo-db1-win.liquibase.net:1433;databaseName=%%D;trustServerCertificate=true
          )