##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  REF_ENV: ${LB_REF_ENVIRONMENT}
  SNAPSHOTS_FOLDER: ${SNAPSHOTS_FOLDER}
  DIFFCHANGELOG_FOLDER: ${DIFFCHANGELOG_FOLDER}

stages:

  Drift-Detection:
    # Check if manual updates were made to the environment since last deployment
    actions:
      - type: liquibase
        command: diff
        cmdArgs: { report-path: "reports", referenceURL: "offline:mssql?snapshot=${SNAPSHOTS_FOLDER}/${ENV}-snapshot.json", format: json }

  Diff-Changelog:
    # Create a changelog that can be used to sync environments
    actions:
      - type: liquibase
        command: diff-changelog
        cmdArgs: { referenceURL: "offline:mssql?snapshot=${SNAPSHOTS_FOLDER}/${ENV}-snapshot.json", changelog-file: "${DIFFCHANGELOG_FOLDER}/${ENV}-to-${REF_ENV}-diffchangelog.mssql.sql" }