##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  TENANT_ID: ${AZURE_TENANT_ID}
  SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
  STORAGE_ACCT: ${AZURE_STORAGE_ACCOUNT}
  CONTAINER: ${AZURE_CONTAINER_NAME}

stages:
  ChangeLog:
    actions:
      - type: liquibase
        command: generate-changelog
        cmdArgs: 
          {  changelog-file: 'generatechangelogs/${ENV}-changelog.xml' }
        
      - type: shell
        command: echo 'Generate Changelog created as generatechangelogs/${ENV}-changelog.xml'