##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  TENANT_ID: ${AZURE_TENANT_ID}
  SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
  STORAGE_ACCT: ${AZURE_STORAGE_ACCOUNT}
  CONTAINER: ${AZURE_CONTAINER_NAME}

stages:
  Snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          {  snapshot-format: json }
        globalArgs: { output-file: 'az://snapshots/${ENV}-azure-snapshot.json' }
        
      - type: shell
        command: echo 'Snapshot created as az://snapshots/${ENV}-azure-snapshot.json'