##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  CLIENT_ID: ${AZURE_CREDS_USR}
  CLIENT_SECRET: ${AZURE_CREDS_PSW}
  TENANT_ID: ${AZURE_TENANT_ID}
  SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
  STORAGE_ACCT: ${LIQUIBASE_AZURE_STORAGE_ACCOUNT}
  CONTAINER: ${AZURE_CONTAINER_NAME}

stages:
  
  AzureDownload:
    # Download existing snapshot from Azure Storage
    actions:
      - type: shell
        command: | 
          az login --service-principal -u ${CLIENT_ID} -p ${CLIENT_SECRET} -t ${TENANT_ID}
          az account set --subscription ${SUBSCRIPTION_ID}
          mkdir -p snapshots
          az storage blob download --account-name ${STORAGE_ACCT} --container-name ${CONTAINER} --name ${ENV}-snapshot.json --file ${WORKSPACE}/snapshots/${ENV}-snapshot.json
          az logout

  Drift-Detection:
    # Check if manual updates were made to the environment since last deployment
    actions:
      - type: liquibase
        command: diff
        cmdArgs: { drift-severity: "1", report-path: "reports", referenceURL: "offline:postgres?snapshot=${CONTAINER}/${ENV}-snapshot.json", format: json }