##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  
stages:
  Snapshot:
    actions:
      - type: liquibase
        command: snapshot
        cmdArgs: 
          {  snapshot-format: json }
        globalArgs: { output-file: 'az://snapshots/${ENV}-azure-snapshot.json' }
        
      - type: shell
        command: echo 'Snapshot created as az://snapshots/${ENV}-azure-snapshot.json'