##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  CONTAINER: ${AZURE_CONTAINER_NAME}

stages:

  Drift-Detection-Shell:
    # Check if manual updates were made to the environment since last deployment
    actions:
      - type: shell
        command: | 
          liquibase --search-path=az://${CONTAINER} diff --reference-url=offline:postgres?snapshot=${ENV}-snapshot.json

#  Drift-Detection-Liquibase:
    # Check if manual updates were made to the environment since last deployment
#    actions:
#      - type: liquibase
#        command: diff
#        cmdArgs: { referenceURL: "offline:postgres?snapshot=${ENV}-snapshot.json" }
#        globalArgs: { search-path: "az://${CONTAINER}" }