##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  REF_ENV: ${LB_REF_ENVIRONMENT}
  CONTAINER: ${AZURE_CONTAINER_NAME}
# SNAPSHOTS_FOLDER: ${SNAPSHOTS_FOLDER}
# DIFFCHANGELOG_FOLDER: ${DIFFCHANGELOG_FOLDER}

stages:

  Drift-Detection:
    # Check if manual updates were made to the environment since last deployment
    # Make sure that search-path is set via an ENV VAR or in the liquibase.properties file.
    # Search-path cannot be set as a globalArg to Flow.
    actions:
      - type: liquibase
        command: diff
        cmdArgs: { referenceURL: "offline:postgres?snapshot=${REF_ENV}-snapshot.json" }
    # cmdArgs: { report-path: "reports", referenceURL: "offline:mssql?snapshot=${SNAPSHOTS_FOLDER}/${REF_ENV}-snapshot.json", format: json }

  Diff-Changelog:
    # Create a changelog that can be used to sync environments
    actions:
      - type: liquibase
        command: diff-changelog
        cmdArgs: { referenceURL: "offline:mssql?snapshot=${SNAPSHOTS_FOLDER}/${REF_ENV}-snapshot.json", changelog-file: "${DIFFCHANGELOG_FOLDER}/${ENV}-to-${REF_ENV}-diffchangelog.mssql.sql" }