##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${LB_ENVIRONMENT}
  CLIENT_ID: ${AZURE_CLIENT_ID}
  CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
  TENANT_ID: ${AZURE_TENANT_ID}
  SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
  STORAGE_ACCT: ${LIQUIBASE_AZURE_STORAGE_ACCOUNT}
  CONTAINER: ${AZURE_CONTAINER_NAME}

stages:

  Drift-Detection:
    # Check if manual updates were made to the environment since last deployment
    actions:
      - type: liquibase
        command: diff
        cmdArgs: { drift-severity: "1", report-path: "reports", referenceURL: "offline:postgres?snapshot=${CONTAINER}/${ENV}-snapshot.json", format: json }