# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: [self-hosted]
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Azure CLI script
#        uses: azure/cli@v2
#        with:
#          azcliversion: latest
#          inlineScript: |
#            az account show