name: Compare Environment Secrets

on:
  workflow_dispatch:
    inputs:
      env1:
        description: 'First environment to compare'
        required: true
        type: environment
      env2:
        description: 'Second environment to compare'
        required: true
        type: environment

jobs:
  fetch-secrets-env1:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env1 }}
    outputs:
      secrets_list: ${{ steps.get-secrets.outputs.secrets }}
    steps:
      - name: Get environment secrets
        id: get-secrets
        run: |
          echo "SECRETS=$(env | awk -F= '{print $1}' | grep -v 'PATH' | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Output secrets list
        run: echo "secrets=${SECRETS}"
  
  fetch-secrets-env2:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env2 }}
    outputs:
      secrets_list: ${{ steps.get-secrets.outputs.secrets }}
    steps:
      - name: Get environment secrets
        id: get-secrets
        run: |
          echo "SECRETS=$(env | awk -F= '{print $1}' | grep -v 'PATH' | tr '\n' ' ')" >> $GITHUB_ENV
      - name: Output secrets list
        run: echo "secrets=${SECRETS}"

  compare-secrets:
    runs-on: ubuntu-latest
    needs: [fetch-secrets-env1, fetch-secrets-env2]
    steps:
      - name: Compare secrets
        run: |
          echo "Secrets in ${{ github.event.inputs.env1 }}: ${{ needs.fetch-secrets-env1.outputs.secrets_list }}" > env1_secrets.txt
          echo "Secrets in ${{ github.event.inputs.env2 }}: ${{ needs.fetch-secrets-env2.outputs.secrets_list }}" > env2_secrets.txt
          
          comm -3 <(sort env1_secrets.txt) <(sort env2_secrets.txt) > secrets_diff.txt || true
          
          echo "Comparison result:"
          cat secrets_diff.txt

      - name: Upload Comparison Result
        uses: actions/upload-artifact@v4
        with:
          name: secrets-comparison
          path: secrets_diff.txt
